kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
- role: worker
- role: worker

# exposing the cluster on the localhost on port 30001
# This is to be done in only kind clusters
# containerPort -> port on which the service is running in the kubernetes
# hostPort -> port on which the service is exposed on the host machine