apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-new
  name: nginx-deploy-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy-new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy-new
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}

# kubectl create deploy nginx-deploy-new --image=nginx:latest --dry-run=client -o yaml > deployment-new.yaml