apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80


# kubectl get pods -o wide
# kubectl get pods --show-labels
# kubectl get pods --selector env=demo